version: '3'
services:
  helen-app:
    build:
      context: .
      args:
        - DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy
    container_name: helen_os_app
    restart: always
    ports:
      - "80:3000"
    env_file:
      - .env
    volumes:
      # Persist Uploads (if any are local)
      - ./public/uploads:/app/public/uploads
